
import 'package:dio/dio.dart';
import 'models/riwayat_model.dart';
class Services {
  Future<RiwayatResponse?> getListHistory(
      int page, String keyword) async {
    try {
      Response response = await Dio().get(
          'https://demo-service.kemenkeu.go.id/perpustakaan/Sirkulasi/GetAll?PageSize=10&Page=$page&keyword=$keyword',
          options: Options(headers: {
            "Content-Type": "application/json",
            "Authorization":
                "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjQyNDc0QTY4NDNBM0VBNTc2MTcyNDE2MTIxMEQ2OTlBMEZFNDQ2Q0EiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJRa2RLYUVPajZsZGhja0ZoSVExcG1nX2tSc28ifQ.eyJuYmYiOjE2NjYyMzE1NDksImV4cCI6MTY2NjI0OTU0OSwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnQua2VtZW5rZXUuZ28uaWQiLCJhdWQiOlsiZnJvbnRlbmQubmFkaW5lIiwiYWdlbmRhLmVrZW1lbmtldSIsInJhcGF0LmVrZW1lbmtldSIsIm5vdGlmaWNhdGlvbi5la2VtZW5rZXUiLCJrZWhhZGlyYW4uZWtlbWVua2V1Iiwib3JnYW5pc2FzaS5ocmlzIiwicHJvZmlsLmhyaXMiLCJqYWJhdGFuLmhyaXMiLCJwYW5na2F0LmhyaXMiLCJkaWtsYXQuaHJpcyIsImtlbHVhcmdhLmhyaXMiLCJwZW5kaWRpa2FuLmhyaXMiLCJla2VtZW5rZXUiLCJrb2xhYm9yYXNpLmVrZW1lbmtldSIsInBlZ2F3YWkuZWtlbWVua2V1Il0sImNsaWVudF9pZCI6ImVrZW1lbmtldS1vYS1kZXYiLCJFbmFibGVNRkEiOiJmYWxzZSIsInN1YiI6IjJiN2EzYmRjLTBlZmYtNGFiMi1iNmI0LWY2MDEzNWRkZTk5OCIsImF1dGhfdGltZSI6MTY2NjIzMTU0NiwiaWRwIjoibG9jYWwiLCJuYW1lIjoiRXJpdGEgWXVsaWFzdHV0aSIsImlkIjoiMTE1Mjc5IiwiYWRkcmVzcyI6IkFwdC4gR2FkaW5nIE5pYXMgUmVzaWRlbmNlIFRvd2VyIENocnlzYW50IE5vLiBDLzE3L0pEIEtlbGFwYSBHYWRpbmcgSmFrYXJ0YSBVdGFyYSIsInBob25lX251bWJlciI6IjA4MTIyNzA3NzQ3NyIsIm5pcCI6IjE5ODUwNzEzMjAxMDEyMjAwMSIsImphYmF0YW4iOiJQZWxha3NhbmEiLCJqZW5pc19qYWJhdGFuIjoiRnVuZ3Npb25hbCBVbXVtIFBOUyIsImtvZGVfb3JnYW5pc2FzaSI6IjM1MDMxMDE4MDIiLCJvcmdhbmlzYXNpIjoiU3ViYmlkYW5nIFBlcmFuY2FuZ2FuIGRhbiBQZW5nZW1iYW5nYW4gQXBsaWthc2kgSSwgQmlkYW5nIEFwbGlrYXNpLCBQdXNhdCBTaXN0ZW0gSW5mb3JtYXNpIGRhbiBUZWtub2xvZ2kgS2V1YW5nYW4sIFNla3JldGFyaWF0IEplbmRlcmFsIiwia29kZV9zYXRrZXIiOiI2NzI5MDYiLCJzYXRrZXIiOiJQdXNhdCBTaXN0ZW0gSW5mb3JtYXNpIGRhbiBUZWtub2xvZ2kgS2V1YW5nYW4iLCJncmF2YXRhciI6Imh0dHBzOi8vYWNjb3VudC5rZW1lbmtldS5nby5pZC9tYW5hZ2UvVXBsb2Fkcy9UaHVtYm5haWxzLzE5ODUwNzEzMjAxMDEyMjAwMS5qcGciLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIxOTg1MDcxMzIwMTAxMjIwMDEiLCJlbWFpbCI6ImVyaXRhLnlAa2VtZW5rZXUuZ28uaWQiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwianRpIjoiNklXZnIwcFJ5OGJCQm95c2d6WmdIZyIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJmcm9udGVuZC5uYWRpbmUiLCJhZ2VuZGEuZWtlbWVua2V1IiwicmFwYXQuZWtlbWVua2V1Iiwibm90aWZpY2F0aW9uLmVrZW1lbmtldSIsImtlaGFkaXJhbi5la2VtZW5rZXUiLCJvcmdhbmlzYXNpLmhyaXMiLCJwcm9maWwuaHJpcyIsImphYmF0YW4uaHJpcyIsInBhbmdrYXQuaHJpcyIsImRpa2xhdC5ocmlzIiwia2VsdWFyZ2EuaHJpcyIsInBlbmRpZGlrYW4uaHJpcyIsImVrZW1lbmtldSIsImtvbGFib3Jhc2kuZWtlbWVua2V1IiwicGVnYXdhaS5la2VtZW5rZXUiXSwiYW1yIjpbInB3ZCJdfQ.boqFephGYZZTxyBjQcAB8IsqTjCdupzjzRYYLJZx2cvJoyEhbrYNZ2GpxIrxi_mywd1TAqhBsk8QC05pMmtIQYiRSWkLCxtmYi1yX75s7AcmS_LmP62uV-BKIklqrAve_GMSMNF_m3hCWPJ-HDssdpAoN3_5P8s_9iW6W3uL9GuUcJ7lKYT3kp-FSpMQdsfijZ1bylVF13B_kKhROmeRhVVX3BaRwDiysBIttF2vetuMpVz5uxCk9Xs41NsXy1lqWPU_JQdRRwE8muqySBfguRsqiOsEGLJaC_Uz3c55lVcptLOsHD4OBQsyInKDHVpGHHMZIZtSTw9Wusfgiz3V6wYeatUmqxt9Vd8HLxQHEepIEOV-FNA5GDwZGfIXLaYEW1mLoMFzcM1fzz_7oKXn8jZMd4KKW0t71dvufPdmFVf2xYvODPZZn5IbrX6rJTHDcGu0l8CnGMlmHKYS04oXmuWXx41GUtoa0sh3YSr3KtfYAeD0rdO2Cv0DJsNcJMFPgkQJO-Q_79IkXooqAtT9Xp_99E_O_IL1VbSD7fGCgpLxJ8QNEl9_QvAEm7qKQd49-cqAmv6kMMbTpQ4YevVQsOGwzHPq_KmG0rX_ThmbhDhghe9ZqqT0N17NI-E_Q92AUjqn5wQtVqSC6WdmiAcWM0YVimUOWzSpggFcQkKUGqs"
          }));
      print('data riwayat');
      if (response.statusCode == 200) {
        print("$response.data");
        return RiwayatResponse.fromJson(response.data);
      } else {
        return null;
      }
    } catch (e) {
      print(e);
      return null;
    }
  }
}


